<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>45.8. 明示的サブトランザクション</title><link rel="stylesheet" type="text/css" href="stylesheet.css" /><link rev="made" href="pgsql-docs@postgresql.org" /><meta name="generator" content="DocBook XSL Stylesheets V1.79.1" /><link rel="prev" href="plpython-database.html" title="45.7. データベースアクセス" /><link rel="next" href="plpython-util.html" title="45.9. ユーティリティ関数" /></head><body><div xmlns="http://www.w3.org/TR/xhtml1/transitional" class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="5" align="center">45.8. 明示的サブトランザクション</th></tr><tr><td width="10%" align="left"><a accesskey="p" href="plpython-database.html" title="45.7. データベースアクセス">Prev</a> </td><td width="10%" align="left"><a accesskey="u" href="plpython.html" title="Chapter 45. PL/Python - Python手続き言語">Up</a></td><th width="60%" align="center">Chapter 45. PL/Python - Python手続き言語</th><td width="10%" align="right"><a accesskey="h" href="index.html" title="PostgreSQL 10.5文書">Home</a></td><td width="10%" align="right"> <a accesskey="n" href="plpython-util.html" title="45.9. ユーティリティ関数">Next</a></td></tr></table><hr></hr></div><div class="sect1" id="PLPYTHON-SUBTRANSACTION"><div class="titlepage"><div><div><h2 class="title" style="clear: both">45.8. 明示的サブトランザクション</h2></div></div></div><div class="toc"><dl class="toc"><dt><span class="sect2"><a href="plpython-subtransaction.html#id-1.8.11.16.3">45.8.1. サブトランザクションのコンテキスト管理</a></span></dt><dt><span class="sect2"><a href="plpython-subtransaction.html#id-1.8.11.16.4">45.8.2. Pythonの旧式バージョン</a></span></dt></dl></div><p><a class="xref" href="plpython-database.html#PLPYTHON-TRAPPING" title="45.7.2. エラーの捕捉">Section 45.7.2</a>で説明したデータベースアクセスによって引き起こるエラーからの復旧は、操作の中の１つが失敗する前に、一部の操作が成功し、エラーからの復旧の後一貫性のないデータが残ってしまうという望ましくない状態を導く可能性があります。
PL/Pythonは明示的サブトランザクションにより、この問題の解法を提供します。
  </p><div class="sect2" id="id-1.8.11.16.3"><div class="titlepage"><div><div><h3 class="title">45.8.1. サブトランザクションのコンテキスト管理</h3></div></div></div><p>2つの口座の間の振替えを実装する関数を考えてみます。
</p><pre class="programlisting">CREATE FUNCTION transfer_funds() RETURNS void AS $$
try:
    plpy.execute("UPDATE accounts SET balance = balance - 100 WHERE account_name = 'joe'")
    plpy.execute("UPDATE accounts SET balance = balance + 100 WHERE account_name = 'mary'")
except plpy.SPIError, e:
    result = "error transferring funds: %s" % e.args
else:
    result = "funds transferred correctly"
plan = plpy.prepare("INSERT INTO operations (result) VALUES ($1)", ["text"])
plpy.execute(plan, [result])
$$ LANGUAGE plpythonu;</pre><p>
2番目の<code class="literal">UPDATE</code>文が例外を発生させる結果となった場合、この関数はエラーを記録しますが、それにもかかわらず最初の<code class="literal">UPDATE</code>はコミットされます。
言い換えると、資金はジョーの口座から引き落とされますが、メアリーの口座には移転しません。
   </p><p>こうした問題を防ぐために、<code class="literal">plpy.execute</code>呼び出しを明示的なサブトランザクションで囲むことができます。
<code class="literal">plpy</code>モジュールは、<code class="literal">plpy.subtransaction()</code>関数で作成される明示的なサブトランザクションを管理するための補助オブジェクトを提供します。
この関数によって作成されるオブジェクトは<a class="ulink" href="http://docs.python.org/library/stdtypes.html#context-manager-types" target="_top">コンテキストマネージャインタフェース</a>を実装します
明示的なサブトランザクションを使用して、上の関数を以下のように書き換えることができます。
</p><pre class="programlisting">CREATE FUNCTION transfer_funds2() RETURNS void AS $$
try:
    with plpy.subtransaction():
        plpy.execute("UPDATE accounts SET balance = balance - 100 WHERE account_name = 'joe'")
        plpy.execute("UPDATE accounts SET balance = balance + 100 WHERE account_name = 'mary'")
except plpy.SPIError, e:
    result = "error transferring funds: %s" % e.args
else:
    result = "funds transferred correctly"
plan = plpy.prepare("INSERT INTO operations (result) VALUES ($1)", ["text"])
plpy.execute(plan, [result])
$$ LANGUAGE plpythonu;</pre><p>
<code class="literal">try/catch</code>の使用がまだ必要なことに注意してください。
さもないと例外がPythonスタックの最上位まで伝播され、関数全体が<span class="productname">PostgreSQL</span>エラーにより中断され、この結果、<code class="literal">operations</code>テーブルには挿入されるはずの行が存在しないことになります。
サブトランザクションのコンテキストマネージャはエラーを捕捉しません。
これはそのスコープの内側で実行されるデータベース操作すべてが、原子的にコミットされるかロールバックされるかだけを保証します。
サブトランザクションブロックのロールバックは、データベースアクセスを元にしたエラーによって引き起こる例外だけではなく、何らかの種類の例外終了でも起こります。
明示的なサブトランザクションブロックの内側で発生した通常のPython例外も同様にサブトランザクションをロールバックさせます。
   </p></div><div class="sect2" id="id-1.8.11.16.4"><div class="titlepage"><div><div><h3 class="title">45.8.2. Pythonの旧式バージョン</h3></div></div></div><p>デフォルトでは、<code class="literal">with</code>キーワードを使用したコンテキストマネージャ構文はPython 2.6で利用可能です。
これより古いバージョンのPythonでPL/Pythonを使用する場合でも、透過性がありませんが、明示的なサブトランザクションを使用することができます。
サブトランザクションマネージャの<code class="literal">__enter__</code>および<code class="literal">__exit__</code>関数を、<code class="literal">enter</code>および<code class="literal">exit</code>という便利な別名を使用して、呼び出すことができます。
資金の振替えを行う関数の例は以下のように記述できます。
</p><pre class="programlisting">CREATE FUNCTION transfer_funds_old() RETURNS void AS $$
try:
    subxact = plpy.subtransaction()
    subxact.enter()
    try:
        plpy.execute("UPDATE accounts SET balance = balance - 100 WHERE account_name = 'joe'")
        plpy.execute("UPDATE accounts SET balance = balance + 100 WHERE account_name = 'mary'")
    except:
        import sys
        subxact.exit(*sys.exc_info())
        raise
    else:
        subxact.exit(None, None, None)
except plpy.SPIError, e:
    result = "error transferring funds: %s" % e.args
else:
    result = "funds transferred correctly"

plan = plpy.prepare("INSERT INTO operations (result) VALUES ($1)", ["text"])
plpy.execute(plan, [result])
$$ LANGUAGE plpythonu;</pre><p>
   </p><div class="note"><h3 class="title">Note</h3><p>コンテキストマネージャはPython 2.5で実装されましたが、このバージョンで<code class="literal">with</code>構文を使用するためには<a class="ulink" href="http://docs.python.org/release/2.5/ref/future.html" target="_top">future文</a>を使用する必要があります。
しかし実装上の問題のためPL/Python関数ではfuture文を使用することができません。
    </p></div></div></div><div class="navfooter"><hr /><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="plpython-database.html">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="plpython.html">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="plpython-util.html">Next</a></td></tr><tr><td width="40%" align="left" valign="top">45.7. データベースアクセス </td><td width="20%" align="center"><a accesskey="h" href="index.html">Home</a></td><td width="40%" align="right" valign="top"> 45.9. ユーティリティ関数</td></tr></table></div></body></html>